### ISSUE TITLE
why is Julia 1.3 incompatible?

### ISSUE THREAD

**Issue by johnnychen94** [JeffFessler/LinearMapsAA.jl#15]
I've tested it locally with Julia 1.3 and the test passes, is that because you disabled Julia 1.3 test in travis? In this case, we could just switch to Github Actions.

My understanding is that "drop CI test for a version" doesn't necessarily mean "being incompatible with a version".

Said that, it's not a big issue to not bring 1.3-compatibility back since Julia 1.3 isn't an LTS version.

**Comment by JeffFessler** [comment]
Hi @johnnychen94 I will look at all your PRs pretty soon.  Thanks for all your work on this!
I don't have any time to try to support old Julia versions and I prefer not to test old versions in CI because that just uses more energy on the CI servers every time we do a push so I would rather keep the carbon footprint lower.  But of course it is fine for users to just modify the Project.toml file locally and try it out on an old Julia version if they want...  Now if there is a better way to communicate this I am open to that...

**Comment by JeffFessler** [comment]
BTW, I didn't understand what you meant by "just switch to Github Actions."
Also, FYI I going to tag the current version of MIRT before starting to work on your PRs, just in case :)

**Comment by johnnychen94** [comment]
Oh, it's just that queuing time is not a "big" issue for Github Actions comparing to Travis; you can run 20 concurrent jobs in Github Actions. https://docs.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits

**Comment by johnnychen94** [comment]
This is not a big issue, so I'll just save us some effort and directly close it without doing any change.
